// Generated by LiveScript 1.3.1
(function(){
  var f, output;
  f = function(x, cb){
    return cb(x * 2);
  };
  output = [];
  while (output.length < 3) {
    f(output.length + 1, fn$);
  }
  console.log(output);
  function fn$(n){
    return output.push(n);
  }
}).call(this);
