// Generated by LiveScript 1.2.0
(function(){
  var root, querystring, http_get, rootURL, wrapSE, wrapSEJSON;
  root = typeof modules != 'undefined' && modules !== null ? modules : this;
  querystring = require('querystring');
  http_get = require('http-request');
  rootURL = 'http://api.stackexchange.com/2.1/';
  wrapSE = root.wrapSE = function(path, defaults, postprocess){
    if (defaults == null) {
      defaults = {};
    }
    if (defaults.site == null) {
      defaults.site = 'stackoverflow';
    }
    if (postprocess == null) {
      postprocess = function(x){
        return x;
      };
    }
    return function(properties, callback){
      var k, ref$, v;
      for (k in ref$ = defaults) {
        v = ref$[k];
        if (properties[k] == null) {
          properties[k] = v;
        }
      }
      console.log(rootURL + path + '?' + querystring.stringify(properties));
      return http_get.get(rootURL + path + '?' + querystring.stringify(properties), function(err, data){
        return callback(postprocess(data.buffer.toString()));
      });
    };
  };
  wrapSEJSON = root.wrapSEJSON = function(path, defaults){
    return wrapSE(path, defaults, JSON.parse);
  };
}).call(this);
